"""empty message

Revision ID: 8656e679cf4b
Revises: cef1e6feaa7b
Create Date: 2019-05-24 12:51:20.634524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8656e679cf4b'
down_revision = 'cef1e6feaa7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'descriptionURL',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('game', 'genre',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('game', 'imageURL',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('game', 'price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('game', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('game', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('game', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('game', 'price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('game', 'imageURL',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('game', 'genre',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('game', 'descriptionURL',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
